# Generated by Django 5.0.2 on 2024-02-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Наименование', 'verbose_name_plural': 'Наименования'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Наименование', 'verbose_name_plural': 'Наименования'},
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_change_date',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
