# Generated by Django 5.0.2 on 2024-02-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0005_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalogApp.contacts', verbose_name='Контакты'),
        ),
    ]
